//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProvisioAPI.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerAccount
    {
        public int Id { get; set; }
        public string ReferenceNumber { get; set; }
        public decimal CustomerBalance { get; set; }
        public string B_AccountNumber { get; set; }
        public string B_AccountName { get; set; }
        public string B_Name { get; set; }
        public string MomoNumber { get; set; }
        public string MomoProvider { get; set; }
        public string TelephoneNumber { get; set; }
        public Nullable<System.DateTime> LastAccessed { get; set; }
        public string Notes { get; set; }
    }
}
