//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProvisioAPI.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class PROVISIODBContext : DbContext
    {
        public PROVISIODBContext()
            : base("name=PROVISIODBContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CustomerAccount> CustomerAccount { get; set; }
        public virtual DbSet<Transactions> Transactions { get; set; }
    
        public virtual ObjectResult<usp_Get_Account_By_BankAccount_Result> usp_Get_Account_By_BankAccount(string b_AccountNumber)
        {
            var b_AccountNumberParameter = b_AccountNumber != null ?
                new ObjectParameter("B_AccountNumber", b_AccountNumber) :
                new ObjectParameter("B_AccountNumber", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_Get_Account_By_BankAccount_Result>("usp_Get_Account_By_BankAccount", b_AccountNumberParameter);
        }
    
        public virtual ObjectResult<usp_Get_Account_By_RefNumber_Result> usp_Get_Account_By_RefNumber(string referenceNumber)
        {
            var referenceNumberParameter = referenceNumber != null ?
                new ObjectParameter("ReferenceNumber", referenceNumber) :
                new ObjectParameter("ReferenceNumber", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_Get_Account_By_RefNumber_Result>("usp_Get_Account_By_RefNumber", referenceNumberParameter);
        }
    
        public virtual ObjectResult<usp_Get_All_Accounts_Result> usp_Get_All_Accounts(string referenceNumber)
        {
            var referenceNumberParameter = referenceNumber != null ?
                new ObjectParameter("ReferenceNumber", referenceNumber) :
                new ObjectParameter("ReferenceNumber", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_Get_All_Accounts_Result>("usp_Get_All_Accounts", referenceNumberParameter);
        }

        public System.Data.Entity.DbSet<ProvisioAPI.Models.CustomerAccountDTO> CustomerAccountDTOes { get; set; }
    }
}
